# Generated by Django 4.0.3 on 2022-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=models.Q('TAMS F(<django.db.models.fields.AutoField>)'), max_length=255)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
    ]
