# Generated by Django 4.0.3 on 2022-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodedevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedevice',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
