# Generated by Django 4.0.3 on 2022-06-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodedevice', '0003_alter_nodedevice_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeDevice',
        ),
    ]
